### PR TITLE
Adding more 'Things'

### PR DESCRIPTION
**Pull request by votemike**

### CODE REVIEW

**Review by tatitati — APPROVED** [review]
Seems ok to me, but I don't feel very solid about this subject, so maybe someone else should have a look. Is the first time I see actually this Torann repo :(

**Comment by Torann** [comment]
I'm going to have to look into this more. There are some cody standards issues and there are no tests. All of which will need to be fixed before this can be merged.

**Comment by votemike** [comment]
@Torann what about it needs to be looked in to more? What are the code standard issues? Does a constructor and a private property need a test?

**Comment by Torann** [comment]
Sorry for being vague in my first message, I was in a rush. Here is a break down.

- All class methods and properties need docblocks. 
- There must be one blank line after the namespace declaration (PSR-2)
- All new or updated context types must have tests or have their existing tests updated

**Comment by votemike** [comment]
OK. That wasn't clear as the GitHub checks all passed. And there's no CONTRIBUTING.md.
What needs to be tested in the context types?

**Pull request closed without merging**
